### ISSUE TITLE
WARNING: DO NOT LOOK AT THE CONSOLE!

### ISSUE THREAD

**Issue by remotevase** [BoxOfDevs/boxofdevs.github.io#1]
DO NOT TRY TO DEBUG THIS!
**CONSIDER YOURSELVES WARNED!**

**Comment by Vaults1** [comment]
I am now super tempted.

**Comment by dragonwocky** [comment]
I already did... Oops :P

**Comment by Vaults1** [comment]
What happened?

**Comment by dragonwocky** [comment]
Warnings about using the mailto function

**Comment by remotevase** [comment]
Not only that... Hundreds of https to http warnings...

**Comment by lavender-sys** [comment]
@remotevase The easy fix for that is to get @TheDragonRing to enable Cloudflare and enable the HTTPS rewrite rule.

**Comment by dragonwocky** [comment]
Will do @Dog2puppy

**Comment by AvgZing** [comment]
@TheDragonRing No need, it all seems to be working fine with the new site.

**Comment by dragonwocky** [comment]
I'll enable Cloudflare anyway :P
