### ISSUE TITLE
Problem with the form

### ISSUE THREAD

**Issue by AvgZing** [BoxOfDevs/boxofdevs.github.io#12]
The application form says head back to https not http for boxofdevs.com after completing it. I think you will see a familiar face soon (when you check the form).

**Comment by dragonwocky** [comment]
There is a reason for that. All the new links I make are https because this weekend I'm setting up cloudflare and ssl.

**Comment by AvgZing** [comment]
Okay

**Comment by AvgZing** [comment]
Did you check form applications? Someone you know very well applied there (you can tell from the email)

**Comment by dragonwocky** [comment]
I'm at school! I'll check them later....

**Comment by dragonwocky** [comment]
Wow -_-

**Comment by remotevase** [comment]
XD

**Comment by dragonwocky** [comment]
"I'm sorry Datboi, but due to not having a GitHub account we cannot accept you into the team."

**Comment by AvgZing** [comment]
lol
