### ISSUE TITLE
Projects page

### ISSUE THREAD

**Issue by AvgZing** [BoxOfDevs/boxofdevs.github.io#13]
@Ad5001 are you gonna add autobuilds of the phar?

**Comment by AvgZing** [comment]
Also, for the projects page the BOD logo is missing

**Comment by Ad5001** [comment]
Since jenkins is setup, I will download it from there. About the logo, it would have been much easier if the boxofdevs.com was under real https, because I used a workaroud and it does not filter everything.

**Comment by AvgZing** [comment]
ok

**Comment by AvgZing** [comment]
Still missing the image... 
Here is the download URL: https://github.com/BoxOfDevs/boxofdevs.github.io/raw/master/images/logo.png
Here is the github image URL: https://github.com/BoxOfDevs/boxofdevs.github.io/blob/master/images/logo.png

**Comment by Ad5001** [comment]
It's in my folder. I have no idea why doesn't it works !

**Comment by Vaults1** [comment]
Closing this because it's old and the projects page is made, if I'm wrong, just reopen.
