### ISSUE TITLE
@Ad5001 and @TheDragonRing

### ISSUE THREAD

**Issue by AvgZing** [BoxOfDevs/boxofdevs.github.io#15]
@Ad5001 I know this is a lot to ask... 
### Instead of having external links, can they be directly linked on the website? More details are below
- [ ] For the wiki, can it be added directly on the page (like it is for Functions)?

- [ ] For the phar, could we have the releases directly on the website? If there is no release, say something like "there are no stable releases yet, but here's the plugins github repository if you want to compile it yourself!"

- [ ] On all the pages, don't forget to add a link to the corresponding github repositoriy.

- [ ]  Also, can we remove all jenkins links? Reason is at the bottom of this message
### Finally, WHERE IS THE LOGO IN THE HEADER?! No need to find it over https, just put it into the img directory of the website on your vps and add a link. how hard could it be?
```file
I expect that @erkam2002's jenkins server will be permanently offline soon, along with all of the rest of his VPSs because he quit MCPE, and replace those jenkins links with the releases. I will be working on my own jenkins server once Turbine Network's vps is finished upgrading (hopefully by next week--shh, dont tell anyone else).
```

**Comment by Ad5001** [comment]
What do you mean by "external links" @TheRoyalBlock ?
About the releases, I'm pretty confused. Should my VPS build them, or Poggit/Jenkins?
About the "no stable release", please note that my VPS DOESN'T check the plugin and Poggit doesn't have any api.
The github link should be fairly easy.
I never added a jenkins link? Was it there before?
The download counter should be fairly easily done when I will know where to download the phar from.
The logo is fixed now.

And about HTTPS, I CANNOT PASS IT BY HTTP FOR ONE REASON:
It's hosted on my download website, rooted with cloudflare. I will be able to when I will have the projects.boxofdevs.com and @TheDragonRing waits for Namecheap.

**Comment by TheRoyalBlock** [comment]
Remind me to come back to this later...

**Comment by TheRoyalBlock** [comment]
At school now, gtg

**Comment by AvgZing** [comment]
External links as in a link going to somewhere else like poggit.
For the releases, no need to build them. We will upload Stable releases to the website (example: 1.0, then 1.1, then 2.0-- you know, like you would do when uploading an update to PocketMine). Tomorrow I will set up Travis-CI scripts on all of our repositories so that we can automatically test them without poggit and without jenkins and without your VPS.
For the no stable releaes, I think that is specified above-- If there is no stable release uploaded to the website, then say there are no stable releases yet, but here's the plugins github repository if you want to compile it yourself!
I am glad that the github link will be easy
Jenkins link: http://boxofdevs.com/projects.html?view=functions for the functions page it says Head to our jenkins server and get the build from last successful artefacts (permalink to latest phar). You can also find an archive of all previous versions.
Download counter: glad you can do it!
Logo: Great!
For https: I said "no need to find it over https" so dont bring https up again other than in private convo with @TheDragonRing

**Comment by Ad5001** [comment]
Few things come in place: 
- Which website are you talking about on line 2?
- Are the plugins only tested with Travis so I download it from there?
- How would I check if plugin is "stable" or not? From Travis again?
- For the jenkins links, my website basicly downloads the README from github and the jenkins link is on it just change the README to change it.

**Comment by AvgZing** [comment]
Oh, so it turns out all of the upload and download links can be changed directly on github by editing the readme. Never mind then, everything is fine. The only things that you have to do:
Link counter (number of times that somebody clicks on the link that says "Download the latest version here!") That link will be added in the readme by me sometime this weekend

**Comment by dragonwocky** [comment]
@TheRoyalBlock @Ad5001 
  - Here is the download counter script (details on how to use are in the comments at the top, it's pretty basic): https://gist.github.com/TheDragonRing/dd2699052d7ea8c4430153cadab0f84d
  - I think there is a way to count downloads stored with GitHub Releases using the GitHub API here: https://help.github.com/articles/getting-the-download-count-for-your-releases/

**Comment by Ad5001** [comment]
@TheDragonRing I have use something similar as the first method, but here, I wanna do something else. I have made a while ago a counter API allowing us to count download easilier: https://api.ad5001.eu/en/online_tools/#counter.
This will allow us to count how many servers uses our plugins instead of downloads.
Althought, we can also use this tool to count the downloads easily with sideloading it.

What do you think of that?

**Comment by dragonwocky** [comment]
Looks great, but what about products that aren't plugins? I know we don't really have any of those finished at the moment, but...

**Comment by Ad5001** [comment]
We would need to implement them differently. That's the only way.

**Comment by AvgZing** [comment]
@TheDragonRing For the ones that are not plugins, then we will def use your script instead so that it works. Like @Ad5001 said, we will implement them differently.

**Comment by dragonwocky** [comment]
Ok.

**Comment by Vaults1** [comment]
Ive got a vps and am setting up jenkins on it if you want to use

**Comment by AvgZing** [comment]
That would be great!

**Comment by AvgZing** [comment]
If it has issues with uptime, I will host a jenkins server on my upcoming virtual machine later this month.
