### ISSUE TITLE
hallo im back kinda...

### ISSUE THREAD

**Issue by Taki21** [BoxOfDevs/boxofdevs.github.io#16]
EDIT: i was inactive this year due to: 7th grade has too much work lol (multitasking and gaming is inefficient) (during august i will be half active due to other taki reasonz xD)

kinda spamming but ill be active during this april break! (hopefully) 
Next year and also summer break ill be fully devoted back to this kewl place lol (hopefully)
ps - i kinda forgot some php so i am relearning lel

see ya peeps soon

**Comment by HimbeersaftLP** [comment]
Yaaaaay

**Comment by AvgZing** [comment]
YAY!! Don't forget to join the BOD Discord!

**Comment by Taki21** [comment]
ok! link? lol

**Comment by Taki21** [comment]
look at edit up lol

**Comment by AvgZing** [comment]
Link is on the website, also I'm to lazy to post the link atm, so I'll l wait for someone what

**Comment by HimbeersaftLP** [comment]
https://discord.gg/PBFQj5K

> multitasking and gaming is inefficient

Couldn't you've told me that before?! 😛

**Comment by Taki21** [comment]
lol

also learning from my own tutorial again xD
https://inactive-to-reactive.github.io/PluginSchoolV2/

**Comment by Ad5001** [comment]
@Taki21 You should take a look at http://learn-mc.ga/MCPE instead ;)

**Comment by AvgZing** [comment]
Yup, while you were away, me and @AD5001 redesigned the entire site!

**Comment by AvgZing** [comment]
@Taki21 you are in the organization already: Sites4Code

**Comment by Taki21** [comment]
damn looks lit! thanks peeps now lemme relearn php xD

**Comment by lavender-sys** [comment]
Lol. The person that taught me has forgotten how to code.

**Comment by AvgZing** [comment]
Lol "same"<-- inside joke with the team only

**Comment by dragonwocky** [comment]
Haha 😜

**Comment by Taki21** [comment]
@Dog2puppy xD

**Comment by Taki21** [comment]
remember this when i had a issue remembering dis:
i was liek was it dis or dis:
```
<?php

or php?>
```

xD

**Comment by Taki21** [comment]
also many kids in skool were eating takis... so... it was a sad 7 months :(
lal

**Comment by HimbeersaftLP** [comment]
LMAO XD

**Comment by lavender-sys** [comment]
@Taki21 is your Discord account professor_taki#5060?

**Comment by Taki21** [comment]
@Dog2puppy ye

@HimbeersaftLP :p

**Comment by Taki21** [comment]
also did u hear about a girl who died on the subway trying to get her phone? was on da news last week (last sunday)

**Comment by HimbeersaftLP** [comment]
@Taki21 No I didn't here about it, gotta look it up :

**Comment by Taki21** [comment]
She died and was from me skool
Whole skool was liek omg

**Comment by HimbeersaftLP** [comment]
Lol

**Comment by AvgZing** [comment]
@taki21 ur school? Wow. I heard about that and now I know what school district u go to XD. You really shouldn't say something like that

**Comment by Vaults1** [comment]
New York?

**Comment by AvgZing** [comment]
Yeah... Both of us (me and taki) live in new York, but we live about 3 hours (via driving) apart from each other.

**Comment by AvgZing** [comment]
Don't forget @remote_vase lives in the same area as me too lol

**Comment by lavender-sys** [comment]
So 3 people in New York? Now I feel left out. I just live under New York time but I'm nowhere near NY.

**Comment by AvgZing** [comment]
@Dog2puppy lol

**Comment by Vaults1** [comment]
I live in Lancashire, England lol. I feel left out. 😛

**Comment by HimbeersaftLP** [comment]
I live in Styria, Austria lol. I feel left out even more. 😛

**Comment by Taki21** [comment]
omg lets calm down on the living stuff xD

**Comment by Taki21** [comment]
now we know where to stalk everyone heheh

**Comment by Vaults1** [comment]
@HimbeersaftLP I read that as "Syria".

**Comment by HimbeersaftLP** [comment]
> @HimbeersaftLP I read that as "Syria".

Big difference xD

However, we have some refugees from Syria here, nothing major, even tough the populists are making it *look like* we have a big problem...

**Comment by Vaults1** [comment]
@taki21 Lancashire is a county. It'll take you ages to find me. 😛

**Comment by AvgZing** [comment]
@ulti0 are you sure about that? XD

**Comment by dragonwocky** [comment]
@TheRoyalBlock you'll never find us!

**Comment by AvgZing** [comment]
Really? Try me.

**Comment by HimbeersaftLP** [comment]
Haha, I'm easy to find, just wait at the railway station at morning on school days 😛

**Comment by lavender-sys** [comment]
@TheDragonRing Who else is there if there's a "us"?

**Comment by Taki21** [comment]
lol just look at our IPs on ImagicalMine forums and locate us by a smaller region.. oops i said too much lol

**Comment by AvgZing** [comment]
This is becoming more like a chatroom, not an actual issue. Closed, but feel free to still talk

**Comment by dragonwocky** [comment]
@Dog2puppy by "us" I just me and all the other BOD members @TheRoyalBlock was searching for, because in the comment before he had said that he would find @Ultie0.

**Comment by Taki21** [comment]
Ooooooohhhh @TheRoyalBlock is acting like a GitHub professional! xD

**Comment by AvgZing** [comment]
🤵 :octocat:

**Comment by lavender-sys** [comment]
@TheDragonRing Okay.
