### ISSUE TITLE
Question: Choose 14 plugins

### ISSUE THREAD

**Issue by remotevase** [BoxOfDevs/boxofdevs.github.io#2]
Everything other than 1 and 2 are based off of the number of downloads on IM Forums. Elytra plugin doesn't work anymore, so that does not count.
1. Functions
2. BoxofBits
3. StatsMe
4. InstaPerms
5. FairTrades
6. Staff Notifier
7.  Levitation
8. File Manager
9. Dimensions
10. SpeedSurvival
11. WinAPI
12. UserTP
13. ?
14. CommandShop
@TheDragonRing @Ultie0 @Ad5001 @Dog2puppy @AmiroEmad @applqpak @HimbeersaftLP @keithkfng @Taki21 @TheKnightGamer Please help me choose 12 13 and 14.

**Comment by remotevase** [comment]
12 can be UserTP

**Comment by remotevase** [comment]
Should CommandShop be one of them? Maybe 14 because its the newest and incomplete

**Comment by remotevase** [comment]
We need 13. Also, We need to create a repository for WinAPI. Why isn't one already created? Is WinAPI complete?

**Comment by HimbeersaftLP** [comment]
WHO THE F*CK DELETED THE WINAPI REPO, I SPENT HOURS WRITING THE WIKI

**Comment by lavender-sys** [comment]
I saw WinAPI 2 days ago. And we used to have 2 pages, but now we have 1.

**Comment by remotevase** [comment]
I never saw a winapi repo... Or did I? I honestly can't remembermember

**Comment by lavender-sys** [comment]
I did, meaning you deleted it.

**Comment by remotevase** [comment]
I definitely did not delete it. I made sure that I only deleted the repositories that were listed in the readme. I even double checked, just in case

**Comment by HimbeersaftLP** [comment]
> I never saw a winapi repo... Or did I? I honestly can't remembermember

https://imgcl.co/plugins/winapi.405/
See the links? They were all forwarding to GitHub, which doesn't exist anymore, which means that I have to write the whole wiki again.... ☹

> I made sure that I only deleted the repositories that were listed in the readme.

Which readme?

**Comment by remotevase** [comment]
The readme for this repository.

**Comment by remotevase** [comment]
Wait... No, I meant the readme for the "archived" repo

**Comment by HimbeersaftLP** [comment]
Nope, it isn't there

**Comment by remotevase** [comment]
Off Topic: Do you have a twitter account?

**Comment by HimbeersaftLP** [comment]
Nope

**Comment by remotevase** [comment]
All other 6 members of BOD chat on Twitter. You should get a twitter.

**Comment by k3ithos** [comment]
Who doesn't have a twitter account :P

**Comment by dragonwocky** [comment]
@HimbeersaftLP doesn't :P

**Comment by HimbeersaftLP** [comment]
I am not allowed to have one, try to persuade my mum if you want to lol

**Comment by dragonwocky** [comment]
Oh lol :(

**Comment by remotevase** [comment]
I said "no personal info will be revealed other than my age. It will only be for gaming and coding, just like my GitHub" then they let me.

**Comment by dragonwocky** [comment]
I actually made my Twitter account by accident while trying to set up a BOD one, and then my parents just let me keep it as long as I didn't let out any personal information other than stuff like my age and nationality.

**Comment by remotevase** [comment]
I just say im a 13 year old from NY. I know @TheDragonRing you are a 12 year old from Australia

**Comment by remotevase** [comment]
See #3 instead
