### ISSUE TITLE
Free website hosting.

### ISSUE THREAD

**Issue by HittmanA** [BoxOfDevs/boxofdevs.github.io#23]
Hey guys, I like the stuff your doing with PocketMine and I wanted to see if you want free website hosting. I have my own VPS running Ubuntu and PHP. I would be more than happy to host your website on my VPS. Migrating to my VPS wouldn't be hard either. Just clone this repo and upload it to my VPS. I can also give you access to the website files on the VPS through FTP.

**Comment by HimbeersaftLP** [comment]
Many BoxOfDevs members (including me) have VPSes with empty space, too, but GitHub pages are convenient because it appears instantly an every member can update the page with ease (sure, thats also possible with a script on a VPS, but that's just more work lol)

We appreciate you offer though
