### ISSUE TITLE
We need more ad spaces

### ISSUE THREAD

**Issue by lavender-sys** [BoxOfDevs/boxofdevs.github.io#24]
We need to add some more ad spaces so we get more impressions. And this step would be so much easier to do if we built this site from scratch using GitHub Pages and Jekyll. With Jekyll, ~~life~~ designing this site would be so much easier, since blog posts would be written in markdown, modifying the Navbar would just be one file, and there would be no need to use Travis to build the site, because Jekyll is built into GitHub Pages.

**Comment by dragonwocky** [comment]
I see your point.

**Comment by Vaults1** [comment]
You need to get visitors first 😛. What's the analytics for this site?

**Comment by AvgZing** [comment]
(on vacation, managed to find data) Analytics: 1 visitor per week.

Side note: I created a test site using jekyll and it looked very bad. Please keep the current site

**Comment by dragonwocky** [comment]
@TheRoyalBlock some Jekyll themes look good, some look bad.

**Comment by lavender-sys** [comment]
@TheRoyalBlock Are you saying my site I just redesigned a few days ago looks bad? Dog2puppy.tk

**Comment by AvgZing** [comment]
Your site looks fine, but (no offense) not as themed towards the name as this. This is box/wood.

**Comment by HimbeersaftLP** [comment]
@TheRoyalBlock Since when are cardboard boxes wood themed?
(Yes I know cardboard is made out of wood)

**Comment by lavender-sys** [comment]
@TheRoyalBlock Well look at pmmp. They took the alpha template from HTML5 and made it Jekyll compatible. And while wood looks nice, I prefer a very clean and easy on the eyes layout, such as jgthms/bulma which is what I used for my site and I'm going to use for the upcoming project (check Discord) admin area.

**Comment by AvgZing** [comment]
I like an appealing themed layout, not an empty, hollow layout.

**Comment by HimbeersaftLP** [comment]
We need to *add* more ad spaces!

(I know where the door is)

**Comment by lavender-sys** [comment]
We have a door?

**Comment by HimbeersaftLP** [comment]
Ofc we do, did noone notice that before?
![Totally legit bod logo](https://i.imgur.com/EsMRx3s.jpg)

**Comment by AvgZing** [comment]
I'm blind!

**Comment by dragonwocky** [comment]
0_o

**Comment by lavender-sys** [comment]
I guess my monitor has too low of a resolution I didn't see that when it was really small on boxofdevs.com. 😆

**Comment by HimbeersaftLP** [comment]
LMAO

**Comment by AvgZing** [comment]
We'll add more ad spaces soon, to random parts of the site

**Comment by AvgZing** [comment]
A side bar, maybe?

**Comment by lavender-sys** [comment]
I got the perfect idea. We spam users with ads. I mean, they probably won’t notice. They’ll just think the ads are our plugins.

**Comment by Vaults1** [comment]
lol this github issue is **public** and that isn't really great for user satisfaction

**Comment by lavender-sys** [comment]
It was a joke...

**Comment by Vaults1** [comment]
oh lol, sorry sarcasm isn't really noticeable online

**Comment by dragonwocky** [comment]
lol have we actually earnt any money at all from those ads?

**Comment by AvgZing** [comment]
Absolutely 0 revenue at the moment.

**Comment by lavender-sys** [comment]
We have 3.6k satoshi which is worth $0.50 USD. We need to reach 100k for minimum payout, due to the BTC network being in a traffic jam.

**Comment by dragonwocky** [comment]
ah. I see.

**Comment by lavender-sys** [comment]
You see what? The network being in a traffic jam?

**Comment by dragonwocky** [comment]
I see that we have 3.6k satoshi (a currency I did not previously know existed), and I see that we need to reach 100k satoshi for minimum payout (because the BTC network is in a traffic jam), and I see that we are getting very little money from the small amount of traffic to our website.

**Comment by lavender-sys** [comment]
1. Satoshi is just smaller parts of bitcoin. 1 satoshi = 0.00000001 BTC

2. A-Ads will add altcoin withdraws soon, so we can avoid the traffic jam entirely.

**Comment by ghost** [comment]
Now back to @Dog2puppy, using JavaScript you can read blog posts from a markdown file and send them as HTML.

**Comment by lavender-sys** [comment]
But what would we do with JS?

**Comment by AvgZing** [comment]
@nathjeid that seems off-topic

**Comment by dragonwocky** [comment]
@nathjeid how do you read the markdown file with JS? We don't need it for blog posts, but I'm curious...

**Comment by AvgZing** [comment]
in fact, GitHub has its own api for converting markdown to html

**Comment by AvgZing** [comment]
Try it: make a repo with gh-pages and no index file, but have the readme. you'll see the contents of the readme displayed

**Comment by lavender-sys** [comment]
So how's that an API?

**Comment by lavender-sys** [comment]
Isn't that just making a new repo?

**Comment by AvgZing** [comment]
alright, buh bye, time for school

**Comment by lavender-sys** [comment]
I'm on a 2 hour delay. Go snow!

**Comment by dragonwocky** [comment]
@TheRoyalBlock I know GitHub has it's own thing, but I'm curious about doing it with plain JS without GitHub's "API". (E.g. a gallery thing, where the JS gets a markdown file that contains an image and description, then displays them all on the same page)

**Comment by lavender-sys** [comment]
@TheDragonRing You could make an NPM package. 

EDIT: nvm, it's already been done.

**Comment by Ad5001** [comment]
With a simple ajax request to the github API would do the trick, althought they have a rate limit.

**Comment by lavender-sys** [comment]
They do have an API. https://developer.github.com/v3/markdown/

**Comment by Ad5001** [comment]
And with plain JS: https://github.com/evilstreak/markdown-js

**Comment by lavender-sys** [comment]
Just asking, but does anyone else use Codenvy?

**Comment by ghost** [comment]
@Ad5001 @Dog2puppy @TheDragonRing This is an example of _showdown_, it is used by Google Cloud Platform and Stackoverflow. https://glitch.com/edit/#!/elated-may

**Comment by ghost** [comment]
@Dog2puppy I have heard of Codenvy..

**Comment by AvgZing** [comment]
@nathjeid Well, that doesn't make it much easier, nor better. You still have image tags, but with markdown you don't get to do beautiful formatting. I don't understand the purpose, but the function is interesting

**Comment by ghost** [comment]
@TheRoyalBlock This is a hold back, why not have a database and work with React?

**Comment by lavender-sys** [comment]
React uses JSX. Vue.js is soooooo much better.

**Comment by AvgZing** [comment]
Nah, I honestly prefer React over Vue @dog2puppy although I've been experimenting with both

**Comment by lavender-sys** [comment]
I love Vue still. I'm using it with webpack to make my project for school.

**Comment by Ad5001** [comment]
Wow. Suprised nobody mentioned the most widespread and fastest js library yet: https://vanilla-js.com

**Comment by lavender-sys** [comment]
I have my doubts about companies like Apple and jQuery using it. 
![screenshot 2018-02-05 at 2 03 21 pm](https://user-images.githubusercontent.com/13684891/35823404-6ba78d52-0a7d-11e8-86ea-c813391fbf88.png)

**Comment by HimbeersaftLP** [comment]
@Dog2puppy I'm quite sure they do :D

**Comment by AvgZing** [comment]
@Dog2puppy They aren't lying

**Comment by lavender-sys** [comment]
So why doesn't jQuery use jQuery?

**Comment by AvgZing** [comment]
What?

**Comment by lavender-sys** [comment]
jQuery uses Vanilla JS. So why don't they use their own product??

**Comment by AvgZing** [comment]
No they don't!

**Comment by HimbeersaftLP** [comment]
@Dog2puppy please don't be offended, but...
![image](https://user-images.githubusercontent.com/16354747/35829592-aaa20f14-0ac3-11e8-8b87-b3d9bdde487d.png)

**Comment by lavender-sys** [comment]
And this shows...?

**Comment by HimbeersaftLP** [comment]
vanilla-js.com is just a parody page that tells people not to use libraries when they Google what "Vanilla JS" is.

**Comment by lavender-sys** [comment]
I thought Vanilla JS was really a library at first. :P

**Comment by ghost** [comment]
What would you guys think of a re-design where everyone has a say.. We can include aTmG, SuperOP535, Thunder33345, and nathjeid (me). This would be great so that you get everyone’s point of view, and I could do the backend because backend rules and @TheRoyalBlock/SuperOP535 can do the design. The rest could pick..

**Comment by ghost** [comment]
@Dog2puppy @TheDragonRing @UltiGB @TheRoyalBlock @HimbeersaftLP @Taki21 @Ad5001 @NiekertDev @InspectorGadget (sorry for the ping but look above).

**Comment by dragonwocky** [comment]
@nathjeid we definitely need a redesign.
I'm happy with it being something that the active members on Discord get a say in as well.
As for you doing the backend... that really depends on the hosting and what you mean by the backend. At the moment, hosting is just GitHub Pages, and I'm not sure if sites hosted with GitHub Pages can have a custom backend... (correct me if I'm wrong)

@BoxOfDevs/members

**Comment by lavender-sys** [comment]
Can we use [Bulma](https://bulma.io) and [Vue](https://vuejs.org/)?

**Comment by dragonwocky** [comment]
I don't see why not.

**Comment by lavender-sys** [comment]
Okay. Also, not related to the site, but can you help me on something? I'm trying to make an NPM package and I know your good at JS.

**Comment by SuperOP535** [comment]
I have a NPM package

**Comment by lavender-sys** [comment]
https://github.com/Dog2puppy/splatoon2.ink-node-api-client/commit/4b85a6afb63d6961f52d6db70ab36e63cacdff38#diff-168726dbe96b3ce427e7fedce31bb0bcR68

**Comment by ghost** [comment]
@Dog2puppy Vue is framework.
@TheDragonRing The backend is in Golang or Node.js, we can host it on Glitch or Heroku as a team..
@TheDragonRing The backend is what serves the frontend and allows for things like dashboard’s, authorizing, and in our case blog posting.

**Comment by ghost** [comment]
_golang ftw_

**Comment by ghost** [comment]
@Dog2puppy Just to make it clear I am good at js too..

**Comment by lavender-sys** [comment]
Why would we use Go? Node.js is the only real dev language.

**Comment by lavender-sys** [comment]
And we can use Vue. I'm using it for a school project as an SPA.

**Comment by ghost** [comment]
@Dog2puppy Node.js is a language and Golang is too. Vue is something that not everyone knows, personally I have messed with Vue, and did not like it. That is why my website is done in React. I will point out that expecting everyone to know Golang is the same too.

**Comment by ghost** [comment]
**Alright, everyone. We can vote now and see what we will use.**
Backend: http://www.strawpoll.me/15014604
Frontend: http://www.strawpoll.me/15014615

**Comment by ghost** [comment]
@Dog2puppy Vue is not for the backend.
@Dog2puppy Vue is for the frontend.

**Comment by lavender-sys** [comment]
I know that.

**Comment by ghost** [comment]
@Dog2puppy Okay, also for anyone to lazy to google. https://vuejs.org

**Comment by dragonwocky** [comment]
@nathfreder I know what a backend is, but with how we have the site hosted currently it's not something we can do. That's all I meant.

**Comment by ghost** [comment]
Vue would be a good choice but not everyone understands it..

**Comment by ghost** [comment]
What do you guys think of doing it all on glitch so that we can all have a part in coding it instead of it being on the main computer?

**Comment by Ad5001** [comment]
As every framework, it'll get outdated in a few mounthes. I'd prefer not using anything but starting from stratch.

**Comment by ghost** [comment]
@Ad5001 That would be okay..

**Comment by lavender-sys** [comment]
I’m fine with using Glitch.

**Comment by dragonwocky** [comment]
Backend I have no experience in, other than a bit of messing with PHP and attempting to customise things like the Anchor CMS, so no opinion on that (I don't think we need it, though).

Frontend, either Vue, Google Polymer, or something built from scratch (probably using jQuery).

@Dog2puppy I can do JS, but I don't know anything about making NPM packages, sorry...

@nathfreder why do you keep thinking we are doing a blog? Far as I know, we're definitely not.

**Comment by lavender-sys** [comment]
@TheDragonRing It’s not really related to NPM with the problem. It’s just with `var`s im having an issue. It’s probably a stupid mistake I made.

**Comment by lavender-sys** [comment]
@nathfreder If you added me to https://glitch.com/edit/#!/elated-may, you can remove me. I had accidentally clicked the button.

**Comment by ghost** [comment]
@TheDragonRing I heard it mentioned, the backend is just what the website runs on.. Every website has a backend of some sort..

**Comment by ghost** [comment]
@Dog2puppy I do not think that I did.. I thought it was just me.

**Comment by ghost** [comment]
@TheDragonRing We can sort out the backend later, we need to make a wireframe first.. (the design)

**Comment by dragonwocky** [comment]
@Dog2puppy sure I can help then. What're you having issues with?

@nathfreder it has been mentioned, but we aren't actually having one. But yeah, we can get to that later - for now let's get a frontend going on GitHub Pages.

**Comment by lavender-sys** [comment]
@TheDragonRing https://github.com/Dog2puppy/splatoon2.ink-node-api-client/commit/4b85a6afb63d6961f52d6db70ab36e63cacdff38#diff-168726dbe96b3ce427e7fedce31bb0bcR68

**Comment by AvgZing** [comment]
@nathfreder Yea, as @TheDragonRing stated already: The majority of our website will be a simple frontend site hosted on gh-pages, simply because it is faster, more reliable, and more public than glitch. The main backend page will be the projects page, which will ideally have automatic phar building for each commit, along with a stable releases section and possibly even an auto-updater. 

Try to move to #26 for the rest of the website redesign discussion.

**Comment by SuperOP535** [comment]
k
