### ISSUE TITLE
The official link is broken

### ISSUE THREAD

**Issue by peter279k** [BoxOfDevs/boxofdevs.github.io#28]
As title, the `https://boxofdevs.com` link is broken.

This should be fixed or removed 👍.

**Comment by AvgZing** [comment]
Shh we were hoping no one would notice... The team's working on getting the domain back, we *accidentally* forgot to pay :grimacing:

**Comment by peter279k** [comment]
Never mind. It will be the common notification 😆 !

**Comment by ghost** [comment]
@TheDragonRing [boxofdevs.community](
https://www.namecheap.com/domains/registration/results.aspx?domain=boxofdevs.community)

**Comment by dragonwocky** [comment]
@nathfreder we plan on getting `.org`

**Comment by ghost** [comment]
@TheDragonRing Cool, will you be using Cloudflare?

**Comment by dragonwocky** [comment]
@nathfreder probably register with Namecheap and then use Cloudflare for DNS, yeah. Won't get it unless this works out, though.

**Comment by ghost** [comment]
I would recommend moving all the current repos to an archive. An attempt to move away from PMMP.

**Comment by InspectorGadget** [comment]
Yes, let's attempt to move away from PMMP since Dktapps and SOFe prefer to work alone and hate to reply to any threads incase of any question. (Happened to me). This made me to walk away from PMMP. Let's revive BOD and prove them that we could do stuffs too. However, we should still have support for PMMP a little bit since there are lots of people in the Discord Chat who are like us.

**Comment by lavender-sys** [comment]
We could always work on big open source projects.

**Comment by dragonwocky** [comment]
Hopefully we'll eventually start one or two "big open source projects" 😉

**Comment by dragonwocky** [comment]
Anyway - closing this issue. The whole website is broken and/or outdated anyway, so this'll be fixed along with everything else when it's redone.

**Comment by ghost** [comment]
@InspectorGadget Dylan tends to work alone, but SOFe is much more involved in the community. Me and him are currently collaborating on a project.
