### ISSUE TITLE
Final 14 Plugins

### ISSUE THREAD

**Issue by remotevase** [BoxOfDevs/boxofdevs.github.io#3]
Everything other than 1 and 2 are based off of the number of downloads on IM Forums. Elytra plugin doesn't work anymore, so that does not count.

1. Functions
2. BoxofBits
3. StatsMe
4. InstaPerms
5. FairTrades
6. Staff Notifier
7. Levitation
8. File Manager
9. Dimensions
10. SpeedSurvival
11. WinAPI
12. UserTP
13. BoxCore
14. CommandShop

**Comment by remotevase** [comment]
What do you think? @BoxOfDevs/plugin-devs

**Comment by Ad5001** [comment]
It's great !

**Comment by HimbeersaftLP** [comment]
Some of them really need some code-cleanup hard lol

**Comment by remotevase** [comment]
@HimbeersaftLP Yeah XD
