### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by HimbeersaftLP** [BoxOfDevs/boxofdevs.github.io#4]
Well, it just shows a blank page xD

Can't we just use a free host and Wordpress instead of copying another company's website?

**Comment by dragonwocky** [comment]
Yeah... Good idea.

Or just make some other static thing.

**Comment by AvgZing** [comment]
Oh no, I'll try to fix this as son as I get all from vacation

**Comment by dragonwocky** [comment]
Ok.
