### ISSUE TITLE
New Site!

### ISSUE THREAD

**Issue by AvgZing** [BoxOfDevs/boxofdevs.github.io#5]
give me feedback! 
@Ad5001 see http://boxofdevs.com/projects.html. It is hard to read, it says

> @Ad5001: This is all you.
You said you would add a projects page with wikis and downloads and all that stuff? Here it is! Other info: The footer has a google translate element, so make sure to add that to all pages. Also, you said that you would host this on a VPS, right? That's why there is the mail_handler.php file because vps's can handle php. Is it possible to synchronise the index.html on the website with index.html on github? We will be adding blog posts to index.html on github sometimes.

Please reply.

**Comment by AvgZing** [comment]
@BoxOfDevs/members What do you think?

**Comment by HimbeersaftLP** [comment]
Great

And #Spam@Ad5001

**Comment by dragonwocky** [comment]
Amazing! Did you go from scratch or find it somewhere?

**Comment by Vaults1** [comment]
@Ad5001 say hi

**Comment by Ad5001** [comment]
Uhhh hi x) I'm having some exams rn so I might start it but the real start for me will be in like 2 days.

**Comment by AvgZing** [comment]
@TheDragonRing I found it somewhere. See discord

**Comment by dragonwocky** [comment]
Yeah just saw that last night...

**Comment by AvgZing** [comment]
UUuuuhhhh the profile pic for everyone is getting reset and, when uploading a new image it says,

> Something went really wrong and we can’t process that picture.

**Comment by dragonwocky** [comment]
Yeah same....

**Comment by dragonwocky** [comment]
I guess we just have to wait :/

I'll reupload the BOD one after school....

**Comment by AvgZing** [comment]
It is after school for me. Its not working...

**Comment by dragonwocky** [comment]
They are all back now!!!!!

**Comment by AvgZing** [comment]
Yeah, as soon as S3 started working again the icons worked too

**Comment by Super35** [comment]
How did u guys do the CNAME

**Comment by Vaults1** [comment]
Create a CNAME file and put the website in, for example: `ulti.gq`

**Comment by AvgZing** [comment]
@Ultie0 actually, go to the settings tab of the repository, and scroll down to the "custom website" field. Input the address there.

**Comment by lavender-sys** [comment]
@TheRoyalBlock both work.

**Comment by AvgZing** [comment]
Yup
