### ISSUE TITLE
Deep Space Objects: Don't ask. Yes, I wrote this by myself.

### ISSUE THREAD

**Issue by AvgZing** [BoxOfDevs/boxofdevs.github.io#8]
Black Holes
Black holes form when the center of a massive star collapses in on itself. 
The collapse can also trigger a supernova.
It is shown that the center of the milky way has a black hole (According to scientific evidence).
There is light created that is invisible to the human eye when a black hole and a star are very close together. This light has a high energy.
Man Made satellites and telescopes can see this light. The satellites and telescopes that NASA launched into space are being used to learn more about the black holes, leading to more answers to questions about the universe. In order for the movement of the stars and the energy expelled, there would have to be a supermassive black hole in the center of our galaxy.
Quasars
A quasar is a massive remote object in space giving off huge amounts of energy. Through telescopes, it looks like a star. This makes quasars hard to find with normal telescopes. There are some theories that suggest that quasars have huge black holes and represent a galaxy evolution stage. A quasar → 
Pulsars
A pulsar is a neutron star1 that is spinning and magnetized. It sweeps pulses of radiation in beams (symmetrical, of course). Sometimes, a pulsar is aligned with Earth and the beams appear to flash on and off as the pulsar spins. How is a pulsar formed? There was a massive star that exploded in a huge supernova which left behind the small dense corpse called a pulsar.
A special pulsar: In one second, the NGC 5907 ULX pulsar emits the same amount of energy that our sun does in three and a half years! This pulsar is the brightest pulsar known to Science.

Neutron Star1: A neutron star is the collapsed core of a large (10–29 solar masses) star. ... They result from the supernova explosion of a massive star, combined with gravitational collapse, that compresses the core past the white dwarf star density to that of atomic nuclei.
Galaxies
The Milky Way galaxy is the galaxy that we live in. The Milky Way galaxy has not thousands, not millions, but Hundreds of Billions of stars, along with lots of leftover dust that can make billions more stars. This is all held together with gravity. Without gravity, every galaxy would fall apart and there would be floating planets randomly throughout the universe. Don’t forget that we would not have a moon. Most of the known galaxies (⅔ to be precise) have a spiral shape with a center of lots of energy and occasional flares. 
Formation
You have most likely heard of the Big Bang. This is a scientific theory about the formation of everything. As you may have guessed, very little is known about how everything was formed. This is a very controversial subject because the rule exists “Matter cannot be created nor destroyed”. You would think that the Big Bang created matter, right? Well, no. In truth, before the Big Bang, there was nothing. There was no space to create anything. The Big Bang Created and stretched the space, expanding the universe. The universe soon cooled, the matter from the Big Bang gathered together slowly, created stars and galaxies. There are many varying theories that we will not discuss here for the sake of time and effort.

Nebula
A nebula is a cloud of dust, and ionized gases. If you have watched a movie like Star Trek, you may have seen that starships hide in thick nebulae. Sorry to break it to you, but that is impossible. A nebula is barely visible to the human eye from earth, and when closer it is larger but no brighter.The brightest known nebula: The Orion Nebula can be viewed with the naked eye.
Variable Stars
A variable star is a star whose brightness fluctuates when seen from earth. There are also other physical changes such as size pulsations, ejection of matter, and changes in spectral1 temperature, color, and type. There are three broad classes for variable stars: Pulsating variables, eclipsing variables, and eruptive variables.  There are 30,000 known variable stars (approx).

UFO’s 
UFO is an acronym for an Unidentified Flying Object. Its most general definition is anything in the sky that is not identifiable as a known object or a known phenomenon. There have been numerous well known UFO Sightings, especially around Mount Rainier in Washington. In many cultures, Unidentified Flying Objects are associated with claims that the person was visited by something from a conspiracy theory or by ET (Extraterrestrial Life). Speaking of Extraterrestrials...
Extraterrestrials
Extraterrestrials are living things from outside the earth’s atmosphere, especially intelligent ones. Although Humans have dreamed up hundreds of thousands of extraterrestrial creatures, we have found none yet. A common example of an extraterrestrial is an alien. What would an extraterrestrial be? Well, there are many possible things that extraterrestrial life could be. The human body is made mainly up of carbon, but when looking at the periodic table you will see that there are other elements with similar chemical properties such as silicon. What would happen if all of the carbon in the body was replaced with silicon? No one knows at the moment.

What do you think?

**Comment by AvgZing** [comment]
This is undergoing updates.

**Comment by dragonwocky** [comment]
0_0

Why exactly...?

**Comment by AvgZing** [comment]
Science project, some info is interesting so I decided to post it there

**Comment by dragonwocky** [comment]
Ok :P
